// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
//
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDug6sjFreIQ36XLH3xQnUP_7Qs9nCpnR4',
    appId: '1:685702362725:web:ad75ab3c54d7cdaf27788c',
    messagingSenderId: '685702362725',
    projectId: 'quizapp-30606',
    authDomain: 'quizapp-30606.firebaseapp.com',
    storageBucket: 'quizapp-30606.firebasestorage.app',
    measurementId: 'G-HBELWJ7QEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9qlH6QVeJcQJTdSA7UN3EqquXDzDg4Pc',
    appId: '1:685702362725:android:0b084e9d792ef67527788c',
    messagingSenderId: '685702362725',
    projectId: 'quizapp-30606',
    storageBucket: 'quizapp-30606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvEsfMkWN9uQlSqz7j0ObBgheXw4Ckg8',
    appId: '1:685702362725:ios:864e6c557286807827788c',
    messagingSenderId: '685702362725',
    projectId: 'quizapp-30606',
    storageBucket: 'quizapp-30606.firebasestorage.app',
    iosBundleId: 'com.alaayq.moashir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsvEsfMkWN9uQlSqz7j0ObBgheXw4Ckg8',
    appId: '1:685702362725:ios:864e6c557286807827788c',
    messagingSenderId: '685702362725',
    projectId: 'quizapp-30606',
    storageBucket: 'quizapp-30606.firebasestorage.app',
    iosBundleId: 'com.alaayq.moashir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDug6sjFreIQ36XLH3xQnUP_7Qs9nCpnR4',
    appId: '1:685702362725:web:cdcad75351d8b96727788c',
    messagingSenderId: '685702362725',
    projectId: 'quizapp-30606',
    authDomain: 'quizapp-30606.firebaseapp.com',
    storageBucket: 'quizapp-30606.firebasestorage.app',
    measurementId: 'G-WW4BN93G67',
  );
}
